### ISSUE TITLE
Support binary data

### ISSUE THREAD

**Issue by snooppy** [Ninja-Squad/DbSetup#34]
Hi there! It would be great if  DbSetup supported binary data. Is it possible to implement?

**Comment by jnizet** [comment]
I just tested inserting a byte array into a varbinary HSQLDB column, and it works fine.
I did the same test for a byte array into a bytea PostgreSQL column, and it works fine too:
```
create table bintest (
  id bigint,
  vb bytea,
  primary key (id));
```
```
        Operation operation =
            sequenceOf(
                deleteAllFrom("bintest"),
                insertInto("bintest")
                    .columns("id", "vb")
                    .values(1L, new byte[] {1, 2, 3})
                    .build());
        new DbSetup(destination, operation).launch();
```
Which database are you using, how is your binary column defined, and what have you tried to insert binary data?
