### ISSUE TITLE
Add Insert.Builder.toString()

### ISSUE THREAD

**Issue by karolchmist** [Ninja-Squad/DbSetup#35]
For easier logging. Please.

**Comment by jnizet** [comment]
Done. I'll release with the fix to #34, if it needs one. Unless you desperatly need this ASAP, but I guess not.

**Comment by karolchmist** [comment]
Thank you! Nothing urgent, just a nice feature to have one day:)

**Comment by jnizet** [comment]
Fix released in 1.5.0. Should be in Maven central soon.
