### ISSUE TITLE
Preffered way to do assertion of data changes

### ISSUE THREAD

**Issue by favetelinguis** [Ninja-Squad/DbSetup#39]
Hi what is the preffered way to assert to content of the database. Im using dbUnit for that right now but I have been missing the DSL style of representing my data. If I can find a nice way to assert the changes I will make the switch right away.

**Comment by jnizet** [comment]
That's out of the scope of DbSetup, which is focused on preparing the database for the tests.
I typically use the methods of the repositories / DAOs to do such assertions. Or dedicated JPQL/SQL queries in the tests.
