### ISSUE TITLE
Warning about annotation during build

### ISSUE THREAD

**Issue by davinkevin** [Ninja-Squad/DbSetup#45]
Hi, 

Since I use DBSetup (very good lib by the way), I have some warning in my build : 
![image](https://cloud.githubusercontent.com/assets/1970922/9709752/9b7d05e2-5531-11e5-9ea9-984a9dc613f7.png)

The annotation seems to be used at some place in code : 
https://github.com/Ninja-Squad/DbSetup/blob/26018c8fc913360be3e9d33c2d1282b3c17c37d9/src/main/java/com/ninja_squad/dbsetup/operation/Insert.java#L197
 
It's very annoying at every build to have this warning popping up.

Thanks for your help

Davin Kevin

**Comment by jnizet** [comment]
Hi @davinkevin 

Thanks for the kind words.

These annotations are used by FindBugs to detect potential bugs in the code by statically analyzing the byte-code. They're not needed at runtime, but Java doesn't know that and thus warns you about the missing annotations.
So the warnings can be safely ignored. But if they're really bothering you, you can also add the following dependency to your project: 'net.sourceforge.findbugs:annotations:1.3.2': http://mvnrepository.com/artifact/net.sourceforge.findbugs/annotations/1.3.2
