### ISSUE TITLE
DDL Operations?

### ISSUE THREAD

**Issue by aadrian** [Ninja-Squad/DbSetup#48]
Hi,

Any plans to support DDL Operations? Create Table, Alter Table, etc?

**Comment by jnizet** [comment]
It's already possible to execute them using a [SqlOperation](http://dbsetup.ninja-squad.com/apidoc/1.6.0/com/ninja_squad/dbsetup/Operations.html#sql%28java.lang.String%29), and I actually do that in the integration tests (see https://github.com/Ninja-Squad/DbSetup/blob/master/src/test/java/com/ninja_squad/dbsetup/integration/CommonOperations.java), but that's not something I would recommend on a real project: tables should pre-exist, and be created using SQL scripts or, better, using a versioning tool like FlywayDB or Liquibase.
What is your use-case? What would you like to be able to do and that can't be done using a SqlOperation?

**Comment by aadrian** [comment]
> ... not something I would recommend on a real project: tables should pre-exist, ...

That might be true for Oracle where there's an admin, but not for admin-less DBs or where tables are managed at runtime by the API or many many scenarios where they don't/can't pre-exist :).

> using a versioning tool like FlywayDB or Liquibase.

Would love to use them, but besides their complexity, Flyway is DB dependent, and Liquibase is just too much XML :(.

> What is your use-case?

To achieve the above in a DB independent manner and without lot of XML, so basically all what DBSetup has on it's first page :).
