### ISSUE TITLE
maven artifact id should not be camel cased

### ISSUE THREAD

**Issue by softdays** [Ninja-Squad/DbSetup#59]
```
<dependency>
    <groupId>com.ninja-squad</groupId>
    <artifactId>DbSetup</artifactId>
    <version${dbsetup.version}</version>
</dependency>
```

should be :

```
<dependency>
    <groupId>com.ninja-squad</groupId>
    <artifactId>dbsetup</artifactId>
    <version${dbsetup.version}</version>
</dependency>
```

**Comment by jnizet** [comment]
Sorry for the late reply. I agree it might look as a poor choice, but it is valid, and changing it now would bring more trouble than good: migration would be painful, it would break semantic versioning, etc. BTW, we're not the only ones to have such an artifact ID. See https://github.com/brettwooldridge/HikariCP for example.
