### ISSUE TITLE
Using RESTART IDENTITY when truncating tables before tests

### ISSUE THREAD

**Issue by rohanagarwal36** [Ninja-Squad/DbSetup#64]
I would be great to have an optional feature of `RESTART IDENTITY` when someone truncates the table in order to insert new data starting from primary key id as 1. That can be helpful in lot of cases.
Also some projects using data types such as SMALLINT for primary key(may be seen rarely, but yet) will find it very useful as they fear primary key to exceed SMALLINT range with insertion of data for each test case without identity being reset.

**Comment by jnizet** [comment]
Hi.

Tanks for the suggestion. I wasn't even aware of this possibility, and understand its usefulness. But this seems to be very specific to PostgreSQL: I haven't found any such thing in the manual for MySQL, Oracle, SQL server or Oracle.

Given that it's PostgreSQL-specific, and that it can be accomplished tricially by using

    Operations.sql("truncate table foo restart identity")

I think I'll pass on this one.

**Comment by rohanagarwal36** [comment]
yes, forgot to mention that this applies only to postgres sql because they use sequences
