### ISSUE TITLE
offer possibility to force skipNextLaunch

### ISSUE THREAD

**Issue by SenCodeMaker** [Ninja-Squad/DbSetup#66]
Hi,

using dbSetupTracker it will verify if the precedent dbSetup is equals with the precedent one before skiping lauch.

This can be an issue when the setup is complex, namely when you're inserting byte array to perform test on photos or DateTime.now() (which is necessarily different from one @test to the other). In these cases launchIfNecessary ends up calling .equals on list of Objects and the results can be sometimes unpredictable. In our case it happen to depend on chances whether the deSetup will be seen as equal to himself or not. 

One solution is to use static values for the operations, in that case they are strictly equal. Another is to put a private static boolean setUpDone,  which is a well known solution, but it bypasses the flow you have setUp for  skipNextLaunch.

Thus, won't it be interesting to create a method launchIfNecessaryIgnoringColumnValues (noun to be discussed :)  ) which doesn't test column values but assume that the dbSetup is the same if the delete+insert statement are syntaxically the same ?

**Comment by jnizet** [comment]
The correct ways IMO would be to
- avoid  using DateTime.now(), or
- to create the DbSetup or the byte array once, and reuse the same instance across tests

Both are fairly easy to do, so I'll pass on this one.
